import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        ink: '#10151B',
        panel: '#171E27',
        parchment: '#EDE6D6',
        brass: '#C08A3E',
        verdigris: '#5B8C7B',
        rust: '#B5482F',
        'on-error': '#690005',
        'on-secondary-fixed-variant': '#1d4f41',
        'on-primary-container': '#412800',
        'outline': '#9d8e7f',
        'on-tertiary-fixed': '#3d0600',
        'on-tertiary-container': '#5d0e00',
        'primary-fixed': '#ffddb5',
        'primary': '#f8bb6a',
        'surface-container': '#1b2026',
        'on-primary': '#462b00',
        'on-secondary': '#00382b',
        'primary-container': '#c08a3e',
        'surface-container-highest': '#30353c',
        'inverse-surface': '#dee3eb',
        'on-primary-fixed': '#2a1800',
        'surface-variant': '#30353c',
        'tertiary': '#ffb4a3',
        'tertiary-fixed': '#ffdad2',
        'on-secondary-fixed': '#002118',
        'primary-fixed-dim': '#f8bb6a',
        'secondary-fixed': '#b9eeda',
        'surface-container-low': '#171c22',
        'inverse-primary': '#825509',
        'on-background': '#dee3eb',
        'tertiary-fixed-dim': '#ffb4a3',
        'on-primary-fixed-variant': '#643f00',
        'error': '#ffb4ab',
        'on-surface-variant': '#d4c4b3',
        'tertiary-container': '#eb7054',
        'outline-variant': '#504538',
        'on-surface': '#dee3eb',
        'surface-container-high': '#252a31',
        'on-secondary-container': '#90c3b0',
        'on-tertiary': '#630f00',
        'surface-tint': '#f8bb6a',
        'surface': '#0f141a',
        'surface-bright': '#353a40',
        'secondary-container': '#205143',
        'surface-container-lowest': '#0a0f14',
        'surface-dim': '#0f141a',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'inverse-on-surface': '#2c3137',
        'background': '#0f141a',
        'secondary-fixed-dim': '#9ed1be',
        'on-tertiary-fixed-variant': '#84250f',
        'secondary': '#9ed1be',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'space-2xl': '2rem',
        'space-2xs': '0.125rem',
        'margin-screen': '1.5rem',
        'space-lg': '1rem',
        'space-md': '0.75rem',
        'space-xs': '0.25rem',
        'gutter': '1px',
        'space-xl': '1.5rem',
      },
      fontFamily: {
        'headline-md': ['Fraunces', 'Libre Caslon Text', 'serif'],
        'body-lg': ['Public Sans', 'sans-serif'],
        'body-md': ['Public Sans', 'sans-serif'],
        'headline-xl': ['Fraunces', 'Libre Caslon Text', 'serif'],
        'headline-lg': ['Fraunces', 'Libre Caslon Text', 'serif'],
        'data-mono-md': ['Spline Sans Mono', 'Space Mono', 'monospace'],
        'headline-sm': ['Fraunces', 'Libre Caslon Text', 'serif'],
        'data-mono-lg': ['Spline Sans Mono', 'Space Mono', 'monospace'],
        'data-mono-sm': ['Spline Sans Mono', 'Space Mono', 'monospace'],
        'body-sm': ['Public Sans', 'sans-serif'],
        'label-caps': ['Spline Sans Mono', 'Space Mono', 'monospace'],
        display: ['Fraunces', 'Libre Caslon Text', 'serif'],
        body: ['Public Sans', 'sans-serif'],
        mono: ['Spline Sans Mono', 'Space Mono', 'monospace'],
      },
      fontSize: {
        'headline-md': ['19px', { lineHeight: '26px', fontWeight: '400' }],
        'body-lg': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-xl': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '400' }],
        'data-mono-md': ['12px', { lineHeight: '16px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '22px', fontWeight: '700' }],
        'data-mono-lg': ['15px', { lineHeight: '20px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'data-mono-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-caps': ['10px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

export default config;
